GITHUB_ACTIONS_TOKEN: "BKA3XOVILJ7IUKVGDWA4EC3H3KUXK"
GITHUB_ORGANIZATION: "vgts"
GITHUB_REPOSITORY_BACKEND: "surgtest-backend-v2"
GITHUB_REPOSITORY_FRONTEND: "surgtest-admin-react"
RUNNER_VERSION: "2.322.0"
RUNNER_DIR: "/home/ubuntu/actions-runner"
ACTION_RUNNER_PATH: "/home/ubuntu/actions-runner/_work"
PYTHON_VERSION: "3.13"
NODE_VERSION: "22"
DEPENDENCY_MANAGEMENT_TOOL: "poetry"
DEPENDENCY_MANAGEMENT_TOOL_TYPE: "pnpm"
PYTHON_APPLICATION_TYPE: "django"
DJANGO_PROJECT_NAME: "surgtest"
UNIX_SOCKETS_PATH: "/var/www/html/unix-sockets"
LOGS_PATH: "/var/log"
PIDS_PATH: "/var/run"
DJANGO_SETTINGS_MODULE: "surgtest.settings.dev.server"
SYSTEM_USER: "ubuntu"
SYSTEM_GROUP: "ubuntu"
NGINX_SITE_NAME: "surgtest.conf"
DOMAIN_NAME: "ansible.vgts.tech"
SITE_NAME: "surgtest"
STATIC_SITE_PATH: "var/www/html"
BUILD_PATH: "surgtest/build"
DIST_PATH: "/surgtest/dist"
PROJECT_NAME: "surgtest-admin-react"
