- name: Check if requirements.txt exists
  stat:
    path: "{{ project_path }}/requirements.txt"
  register: requirements_stat

- name: Check if pyproject.toml exists
  stat:
    path: "{{ project_path }}/pyproject.toml"
  register: pyproject_stat

- name: Install python{{PYTHON_VERSION}}-dev if hiredis is in requirements.txt
  apt:
    name:
      - build-essential
      - libffi-dev
    state: present
  when: 
    - requirements_stat.stat.exists and "'hiredis' in lookup('file', project_path + '/requirements.txt')"

- name: Install python{{PYTHON_VERSION}}-dev if hiredis is in pyproject.toml
  apt:
    name:
      - build-essential
      - libffi-dev
    state: present
  when: 
    - pyproject_stat.stat.exists and "'hiredis' in lookup('file', project_path + '/pyproject.toml')"
    