- name: Ensure system is updated
  apt:
    update_cache: yes
    upgrade: yes

- name: Install Node.js and npm (required for pnpm)
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
    apt-get install -y nodejs
  args:
    executable: /bin/bash

- name: Install pnpm globally using npm
  shell: "npm install -g pnpm"
  args:
    executable: /bin/bash
  register: pnpm_install
  changed_when: "'pnpm' in pnpm_install.stdout"

- name: Verify pnpm installation
  shell: "pnpm --version"
  register: pnpm_version
  changed_when: false

- name: Show installed pnpm version
  debug:
    msg: "pnpm version installed: {{ pnpm_version.stdout }}"
